// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for local development, fallback to production
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wbuaiwzpsehomogbbyfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndidWFpd3pwc2Vob21vZ2JieWZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTA2NTgsImV4cCI6MjA2NTk4NjY1OH0.HlgBuiA5mAnhGG4_T4Ne6zq12I-w5pdK8ebBpOJP2U8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);